name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Only run on version tags like v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure Poetry for PyPI
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

    - name: Build and Publish package to PyPI
      run: poetry publish --build
