name: Publish to TestPyPI

on:
  push:
    tags:
      - 'v*'  # Runs only on version tags like v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Checks out your repository code

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a general Python 3 version

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH # Add Poetry to PATH for subsequent steps

    - name: Configure Poetry for TestPyPI
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry config pypi-token.testpypi ${{ secrets.TESTPYPI_API_TOKEN }}
      env:
        TESTPYPI_API_TOKEN: ${{ secrets.TESTPYPI_API_TOKEN }}

    - name: Build and Publish package to TestPyPI
      run: poetry publish --build --repository testpypi
